apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-nginx.fullname" . }}
  labels:
    app: {{ include "simple-nginx.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-nginx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-nginx.name" . }}
    spec:
      containers:
        - name: nginx-{{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: {{ include "simple-nginx.fullname" . }}-html
